### PR TITLE
Get a default playlist when none has been defined

### PR DESCRIPTION
**Pull request by nclavaud**
If playlist_id is not set in the app parameters, the main page will
fail with error code 500. This fix will retrieve the playlist with
the lowest id instead when no playlist_id has been set.

Fixes issue #21

### CODE REVIEW

**Comment by kimlai** [comment]
This seems like a lot of code for a missing parameter. Maybe it'd be better to make the [melikeyradio:currentPlaylist:update](https://github.com/kimlai/melikeyradio/blob/master/src/MeLikey/RadioBundle/Command/UpdateCurrentPlaylistCommand.php) a bit more robust, and call it when loading the fixtures.

Plus, this won't handle the case where there simply is no playlist.

**Comment by kimlai** [comment]
Or maybe using a parameter for this is simply not a good approach. I dunno.

**Comment by nclavaud** [comment]
Sure it's a hack. Best option IMO would be to be able to _star_ / _flag_ the main playlist.

**Comment by nclavaud** [comment]
So old :wave:

**Pull request closed without merging**
